// 場所: 'hama'（ひだまり浜・ハワイの入り江）か 'numa'（ひだまり沼）。
// 選びかた: URL の ?place= → 前回の場所 → ページの既定（meta）→ 浜。場所ごとに、記録（セーブ）も別。
// 開くたびに、まず「どちらの釣り場から始めますか」をえらんでもらう（裏では前回の場所を読み込んでおく）。
// えらんだあと・旅の地図で移動したあとは、URL に ?place= がつくので、えらぶ画面は出さない。
import { L } from './i18n.js';
const KEY = 'hidamari-place';
const IDS = ['hama', 'numa'];

let choose = false, last = null;
function pick() {
  let p = null;
  try { p = new URLSearchParams(location.search).get('place'); } catch (e) { /* ignore */ }
  if (IDS.includes(p)) { try { localStorage.setItem(KEY, p); } catch (e) { /* ignore */ } return p; }
  // ?go=1（すぐ始める）・?map=1（旅の地図から）のときは、えらぶ画面を出さない（前回の釣り場を読みこむ）
  let quick = false;
  try { const q = new URLSearchParams(location.search); quick = q.get('go') === '1' || q.get('map') === '1'; } catch (e) { /* ignore */ }
  choose = !quick;
  try { p = localStorage.getItem(KEY); } catch (e) { p = null; }
  if (IDS.includes(p)) last = p;
  else { try { last = localStorage.getItem('hidamari-numa-v1') ? 'numa' : localStorage.getItem('hidamari-hama-v1') ? 'hama' : null; } catch (e) { /* ignore */ } }
  if (!IDS.includes(p) && last) p = last;   // 場所の記憶がない（前の版で遊んだ）ときは、記録のある釣り場
  return IDS.includes(p) ? p : fallback();
}
// 既定の釣り場: ページに <meta name="hidamari-place" content="numa"> があれば、それ（公開する版ごとに変えられる）。なければ浜
function pageDefault() {
  let d = null;
  try { const m = document.querySelector('meta[name="hidamari-place"]'); d = m && m.getAttribute('content'); } catch (e) { /* ignore */ }
  return IDS.includes(d) ? d : null;
}
function fallback() { return pageDefault() || 'hama'; }

export const PLACE_ID = pick();
export const FIRST_VISIT = choose;   // 開いたときに、釣り場をえらぶ画面を出す
export const LAST_PLACE = last;     // 前回の釣り場（はじめてなら null）
export const PLACES = {
  hama: {
    id: 'hama', title: L('ひだまり浜', 'Hidamari Cove'), sub: L('ハワイの入り江の釣り', 'Fishing a Hawaiian cove'), saveKey: 'hidamari-hama-v1', pic: 'hidamari-hama',
    // 旅の地図: 場所（オアフ島の東、ラニカイの入り江）と、現地の時刻の基準
    geo: { lat: 21.392, lon: -157.716, tz: 'Pacific/Honolulu', region: L('ハワイ・オアフ島　ラニカイの入り江', 'Lanikai, Oʻahu, Hawaiʻi'), short: L('オアフ島', 'Oʻahu'), mark: '浜', en: 'HAWAII' },
    desc: L('ハワイの穏やかな入り江で、ウキを浮かべて波の音を聞く。澄んだ海にサンゴとヤッコ、キイロハギ。three.js で作った、のんびり南の海釣りゲーム。', 'Float a bobber in a calm Hawaiian cove and listen to the waves. Clear water, coral, angelfish and yellow tangs. A slow, peaceful fishing game made with three.js.'),
    startBefore: 0.4, water: L('浜', 'cove'), boat: false, neighbor: false, cat: false, tank: true,
    lead: L('ハワイの、小さな入り江。<br>澄んだ水の底に、サンゴと、色あざやかな魚たち。<br>ウキをなげて、波の音を聞く時間をどうぞ。', 'A small cove in Hawaiʻi.<br>Coral and bright fish under clear water.<br>Cast your bobber and listen to the waves.'),
    rodHera: L('のべ竿', 'Pole'), rodHeraSub: L('手前・リールなし', 'Close in · no reel'), rodLine: L('リール竿 ⇄ のべ竿（リールなし）', 'Reel rod ⇄ pole (no reel)'), heraTip: null,
    legendSize: L('ウルアの貫禄。とてつもない大物！', 'A true ulua. An enormous fish!'), legendBadge: L('海のぬし！', 'Lord of the sea!'), zukan: L('ひだまり浜の住人たち', 'Residents of Hidamari Cove'),
    credit: L('ひだまり浜 — three.js で作った、手続き生成だけの小さな釣り場。<br>景色・魚・音はすべてプログラムで生成しています。', 'Hidamari Cove — a small fishing spot made with three.js.<br>The scenery, fish and sounds are all generated by code.'),
    allToast: L('図鑑コンプリート！浜の主になった', 'Field guide complete! You are the master of the cove'), legendToast: L('ウルアを釣り上げた！　語りつがれるぞ', 'You landed the ulua! They will tell this story for years'), junkToast: L('ごみを持ち帰った。浜がきれいになった！', 'You took the litter home. The beach is a little cleaner!'),
    nushiToast: L('青い底のほうで、とても大きな影が横ぎった…', 'Down in the blue, a huge shadow passed by…'),
    rainbowToast: L('通り雨のあとの空に、にじがかかった', 'A rainbow after the passing shower'),
    thunderToast: L('遠くで雷が鳴った…大きな魚が動きだしそう', 'Thunder in the distance… the big fish may start to move'),
  },
  numa: {
    id: 'numa', title: L('ひだまり沼', 'Hidamari Pond'), sub: L('田舎の釣り', 'Countryside fishing'), saveKey: 'hidamari-numa-v1', pic: 'hidamari-numa',
    geo: { lat: 39.16, lon: 140.49, tz: 'Asia/Tokyo', region: L('秋田県南部　湯沢のあたり', 'Near Yuzawa, southern Akita, Japan'), short: L('秋田県', 'Akita'), mark: '沼', en: 'AKITA' },
    desc: L('山あいの小さな沼で、ウキを浮かべてぼんやり待つ。three.js で作った、のんびり田舎釣りゲーム。', 'Float a bobber on a small mountain pond and simply wait. A slow, peaceful countryside fishing game made with three.js.'),
    startBefore: 0.7, water: L('沼', 'pond'), boat: true, neighbor: true, cat: true, tank: false,
    lead: L('山あいの小さな沼。<br>夕暮れ前の、やわらかな光。<br>ウキをなげて、ぼんやり待つ時間をどうぞ。', 'A small pond in the hills.<br>Soft light before dusk.<br>Cast your bobber and take your time.'),
    rodHera: L('へら竿', 'Hera pole'), rodHeraSub: L('手前・のべ竿', 'Close in · fixed line'), rodLine: L('リール竿 ⇄ へら竿（リールなし）', 'Reel rod ⇄ hera pole (no reel)'), heraTip: L('へら竿には練りエサがよく合います', 'Dough bait suits the hera pole'),
    legendSize: L('沼のぬしの貫禄。とてつもない大物！', 'The lord of the pond. An enormous fish!'), legendBadge: L('沼のぬし！', 'Lord of the pond!'), zukan: L('ひだまり沼の住人たち', 'Residents of Hidamari Pond'),
    credit: L('ひだまり沼 — three.js で作った、手続き生成だけの小さな釣り場。<br>景色・魚・音はすべてプログラムで生成しています。', 'Hidamari Pond — a small fishing spot made with three.js.<br>The scenery, fish and sounds are all generated by code.'),
    allToast: L('図鑑コンプリート！沼の主になった', 'Field guide complete! You are the master of the pond'), legendToast: L('沼のぬしを釣り上げた！　語りつがれるぞ', 'You landed the lord of the pond! They will tell this story for years'), junkToast: L('ごみを持ち帰った。沼がきれいになった！', 'You took the litter home. The pond is a little cleaner!'),
    nushiToast: L('水の底で、なにか大きなものが動いた…', 'Something big moved at the bottom…'),
    rainbowToast: L('雨あがりの空に、にじが出た', 'A rainbow after the rain'),
    thunderToast: L('遠くで雷が鳴った…ナマズが動きだしそう', 'Thunder in the distance… the catfish may start to move'),
  },
};
export const PLACE = PLACES[PLACE_ID];
export const PLACE_IDS = IDS;
// 旅の地図の「準備中」のピン（これから増える釣り場の予告。位置は仮）
export const SOON = [{ lat: 51.4, lon: -116.2 }, { lat: -44.9, lon: 168.7 }];
