// 魚種データ（ゲーム本体の src/species.js から tools/build-species.mjs で生成）
export const SPECIES = [
{"id":"funa","name":"フナ","ruby":"ふな","latin":"Carassius langsdorfii","cm":[9,33],"rarity":1,"kind":"swim","season":null,"legend":false,"junk":false,"nibble":[1,3],"desc":"「釣りはフナに始まりフナに終わる」。のんびり暮らす沼のおなじみさん。","rumor":null,"biteText":"ツン、ツンと小さくつついて、すっとウキを引き込む","bite":{"tick":{"amp":-0.03,"dur":0.3,"up":0.28,"gap":[0.6,1.4],"snd":"tick"},"end":{"sink":-0.4,"rate":14,"snd":"sink"}},"layer":[0.35,0.95],"bottom":false,"active":{"dawn":1.3,"day":1,"dusk":1.3,"night":0.55}},
{"id":"koi","name":"コイ","ruby":"こい","latin":"Cyprinus carpio","cm":[28,78],"rarity":2,"kind":"swim","season":null,"legend":false,"junk":false,"nibble":[2,4],"desc":"沼のぬし級。ひげを揺らして底をさぐる、引きの強い大物。","rumor":null,"biteText":"ウキがゆっくり横へ動いて、ぐーっと深く引きずり込む","bite":{"tick":{"amp":-0.07,"dur":0.7,"up":0,"gap":[0.8,1.7],"drift":0.05,"snd":"yure","vib":16},"end":{"sink":-0.6,"rate":8,"drift":0.14,"ripple":0.8,"splash":0.26,"snd":"heavy"}},"layer":[0.7,1.5],"bottom":false,"active":{"dawn":1,"day":0.8,"dusk":1.3,"night":1.25}},
{"id":"tanago","name":"タナゴ","ruby":"たなご","latin":"Acheilognathus melanogaster","cm":[5,10],"rarity":2,"kind":"swim","season":null,"legend":false,"junk":false,"nibble":[3,6],"desc":"婚姻色のひれが夕陽にきらめく、小さな宝石。そっと合わせて。","rumor":null,"biteText":"チクチクと細かく震えて、ウキがふっと持ち上がる（食い上げ）","bite":{"tick":{"amp":-0.013,"dur":0.13,"up":0.4,"gap":[0.2,0.55],"snd":"chiku","vib":6},"end":{"lift":0.035,"liftT":0.45,"sink":-0.13,"rate":12,"snd":"soft"}},"layer":[0.15,0.55],"bottom":false,"active":{"dawn":1.1,"day":1,"dusk":1.4,"night":0.35}},
{"id":"imori","name":"イモリ","ruby":"いもり","latin":"Cynops pyrrhogaster","cm":[7,14],"rarity":2,"kind":"newt","season":null,"legend":false,"junk":false,"nibble":[1,2],"desc":"お腹の赤は毒のしるし。井戸や田んぼを守る「井守」。そっと逃がしてあげよう。","rumor":null,"biteText":"ウキがゆらゆらと揺れて、ゆっくり沈んでいく","bite":{"tick":{"amp":-0.016,"dur":0.85,"up":0.4,"gap":[0.9,1.8],"drift":0.03,"snd":"yure","vib":8},"end":{"sink":-0.2,"rate":5,"snd":"soft"}},"layer":[0.1,1.1],"bottom":true,"active":{"dawn":1,"day":1.1,"dusk":1,"night":0.8}},
{"id":"dojo","name":"ドジョウ","ruby":"どじょう","latin":"Misgurnus anguillicaudatus","cm":[8,21],"rarity":2,"kind":"swim","season":null,"legend":false,"junk":false,"nibble":[1,3],"desc":"泥の中の名人。ひげでエサをさぐり、ぬるりと身をくねらせる。","rumor":null,"biteText":"ブルブルと震えて、ウキを底のほうへ引っぱる","bite":{"tick":{"amp":-0.02,"dur":0.6,"up":0.2,"shake":0.011,"gap":[0.5,1.1],"snd":"buru","vib":20},"end":{"sink":-0.3,"rate":9,"shake":0.008,"drift":0.05,"snd":"sink"}},"layer":[0.2,1.5],"bottom":true,"active":{"dawn":1,"day":0.8,"dusk":1.2,"night":1.3}},
{"id":"zarigani","name":"ザリガニ","ruby":"ざりがに","latin":"Procambarus clarkii","cm":[6,12],"rarity":1,"kind":"crayfish","season":null,"legend":false,"junk":false,"nibble":[2,3],"desc":"子どものころの冒険の相棒。はさみに気をつけて！","rumor":null,"biteText":"ウキがずるずると横へ引きずられて、ゆっくり沈む","bite":{"tick":{"amp":-0.01,"dur":0.95,"up":0.2,"drift":0.09,"gap":[0.8,1.6],"snd":"zuru","vib":12},"end":{"sink":-0.25,"rate":6,"drift":0.22,"snd":"soft"}},"layer":[0.1,1.3],"bottom":true,"active":{"dawn":1,"day":0.9,"dusk":1.3,"night":1.1}},
{"id":"namazu","name":"ナマズ","ruby":"なまず","latin":"Silurus asotus","cm":[28,62],"rarity":3,"kind":"swim","season":null,"legend":false,"junk":false,"nibble":[2,3],"desc":"雷雨の前に騒ぐと言われる沼のぬし。ぬるぬる、のっそり。","rumor":null,"biteText":"ゴンッと重く突いて、ウキごと一気に引き込む","bite":{"tick":{"amp":-0.1,"dur":0.26,"up":0.1,"gap":[1,2],"snd":"gon","vib":30},"end":{"sink":-0.75,"rate":24,"ripple":1.1,"splash":0.4,"snd":"heavy"}},"layer":[1.1,2],"bottom":false,"active":{"dawn":1.2,"day":0.3,"dusk":1.5,"night":2}},
{"id":"nishiki","name":"ニシキゴイ","ruby":"にしきごい","latin":"Cyprinus rubrofuscus","cm":[35,66],"rarity":4,"kind":"swim","season":null,"legend":false,"junk":false,"nibble":[3,5],"desc":"紅白の錦。出会えたらきっと良いことがある、沼の宝もの。","rumor":null,"biteText":"ふわっとウキを持ち上げてから、ぐいっと引き込む","bite":{"tick":{"amp":0.03,"dur":0.8,"up":1,"gap":[0.9,1.8],"snd":"fuwa","vib":10},"end":{"lift":0.04,"liftT":0.5,"sink":-0.5,"rate":9,"ripple":0.7,"snd":"heavy"}},"layer":[0.45,1.05],"bottom":false,"active":{"dawn":1.4,"day":0.9,"dusk":1.5,"night":0.5}},
{"id":"hibuna","name":"ヒブナ","ruby":"ひぶな","latin":"Carassius auratus (red)","cm":[14,31],"rarity":3,"kind":"swim","season":"spring","legend":false,"junk":false,"nibble":[1,3],"desc":"緋色にかがやく、春だけのフナ。水の中で、ぽっとあかりがともったよう。","rumor":"春、水がぬるむころ、緋色のフナを見たという話がある……。","biteText":"フナのように、ツン、ツンと小さくつついて、すっと沈める","bite":{"tick":{"amp":-0.03,"dur":0.3,"up":0.28,"gap":[0.6,1.4],"snd":"tick"},"end":{"sink":-0.4,"rate":14,"snd":"sink"}},"layer":[0.3,0.9],"bottom":false,"active":{"dawn":1.4,"day":1,"dusk":1.3,"night":0.4}},
{"id":"unagi","name":"ウナギ","ruby":"うなぎ","latin":"Anguilla japonica","cm":[40,88],"rarity":4,"kind":"swim","season":"summer","legend":false,"junk":false,"nibble":[2,4],"desc":"夏の夜、泥のなかから出てくる、ぬるりと長い影。引きは力強い。","rumor":"夏の夜、底のほうで長いものが動いていた……という話がある。","biteText":"ウキがじわじわ引かれて、ぐぐっと沈んでいく","bite":{"tick":{"amp":-0.05,"dur":0.45,"up":0,"gap":[0.7,1.5],"drift":0.04,"snd":"zuru","vib":18},"end":{"sink":-0.5,"rate":9,"drift":0.12,"shake":0.005,"ripple":0.7,"splash":0.22,"snd":"heavy"}},"layer":[0.9,2.2],"bottom":true,"active":{"dawn":0.9,"day":0.12,"dusk":1.4,"night":2.4}},
{"id":"herabuna","name":"ヘラブナ","ruby":"へらぶな","latin":"Carassius cuvieri (hera)","cm":[26,52],"rarity":2,"kind":"swim","season":"autumn","legend":false,"junk":false,"nibble":[3,5],"desc":"へら竿のふるさと。秋は荒食いで、ふだんは用心深いのに、エサをふわっと吸いこむ。","rumor":"秋、大きな平たいフナがエサを吸いこんでいた……という話がある。","biteText":"ウキがじわっと戻ったり沈んだり。すっと入ったら合わせどき","bite":{"tick":{"amp":-0.02,"dur":0.5,"up":0.5,"gap":[0.8,1.7],"snd":"yure","vib":8},"end":{"sink":-0.32,"rate":12,"snd":"soft"}},"layer":[0.5,1.3],"bottom":false,"active":{"dawn":1.3,"day":1,"dusk":1.3,"night":0.4}},
{"id":"wakasagi","name":"ワカサギ","ruby":"わかさぎ","latin":"Hypomesus nipponensis","cm":[6,14],"rarity":3,"kind":"swim","season":"winter","legend":false,"junk":false,"nibble":[3,6],"desc":"冬の沼にだけやってくる、小さな銀色のさかな。冷たい水で、ちいさく群れる。","rumor":"雪の季節、銀色の小さな群れが沈んでいた……という話がある。","biteText":"コツコツと小さく震えて、ウキがふわっと動く","bite":{"tick":{"amp":-0.012,"dur":0.14,"up":0.6,"gap":[0.2,0.5],"snd":"chiku","vib":6},"end":{"lift":0.02,"liftT":0.35,"sink":-0.1,"rate":12,"snd":"soft"}},"layer":[0.7,1.6],"bottom":false,"active":{"dawn":1.3,"day":1,"dusk":1.2,"night":0.3}},
{"id":"nushi","name":"沼のぬし","ruby":"ぬまのぬし","latin":"Silurus asotus (senex)","cm":[88,118],"rarity":4,"kind":"swim","season":null,"legend":true,"junk":false,"nibble":[3,5],"desc":"何十年も沼の底に棲むという、苔むした大ナマズ。雨の夜だけ、深みから姿をあらわす。","rumor":"雨の夜、ミミズを深く沈めると、大きな影が寄ってくる……という噂。","biteText":"ウキが、ゆっくり、底へ引きずりこまれていく……","bite":{"tick":{"amp":-0.12,"dur":1.2,"up":0,"gap":[1.4,2.4],"drift":0.08,"snd":"gon","vib":40},"end":{"sink":-0.9,"rate":4,"ripple":1.3,"splash":0.5,"drift":0.2,"snd":"heavy"}},"layer":[1.4,2.4],"bottom":false,"active":{"dawn":0.8,"day":0.1,"dusk":1,"night":2.4}},
{"id":"boot","name":"長靴","ruby":"ながぐつ","latin":"Calceus rusticus","cm":[24,34],"rarity":1,"kind":"boot","season":null,"legend":false,"junk":true,"nibble":[1,1],"desc":"誰かの落とし物。中に小さなカエルがいた気がする……。","rumor":null,"biteText":null,"bite":null,"layer":[0.3,0.5],"bottom":false,"active":{"dawn":1,"day":1,"dusk":1,"night":1}}
];
export const BY_ID = Object.fromEntries(SPECIES.map((s) => [s.id, s]));
